default: &default
  canonical_host: "www.example.com"
  system_email: "no-reply@example.com"
  # memcached:
  #   servers: ["127.0.0.1:11211"]
  #   namespace: "example"
  upyun:
    switch: 'on' # to support file upload, change this to 'on'
    operator_name: 'lenage'
    operator_password: 'hicape.com'
    bucket: 'hicape'
    bucket_domain: 'hicape.b0.upaiyun.com'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: 'project_rabel'
