default: &default
  canonical_host: "www.example.com"
  system_email: "no-reply@example.com"
  # memcached:
  #   servers: ["127.0.0.1:11211"]
  #   namespace: "example"
  upyun:
    switch: 'off' # to support file upload, change this to 'on'
    operator_name: ''
    operator_password: ''
    bucket: ''
    bucket_domain: ''

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: 'project_rabel'
